// <auto-generated />
using System;
using Food.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Food.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Food.Entity.About", b =>
                {
                    b.Property<int>("about_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("about_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("about_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("about_Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("about_id");

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            about_id = 1,
                            about_Description = "The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way. \n \n When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove,the headline of Alphabet Village and the subline of her own road,the Line Lane.Pityful a rethoric question ran over her cheek,then she continued her way.",
                            about_Title = "Footwear the leading eCommerce Store around the Globe",
                            about_Url = "https://www.youtube.com/watch?v=F1vcruph8JA"
                        });
                });

            modelBuilder.Entity("Food.Entity.Bills", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_Cancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_Confirmation")
                        .HasColumnType("bit");

                    b.Property<DateTime>("bill_DatetimeOrder")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bill_Delivered")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_Delivering")
                        .HasColumnType("bit");

                    b.Property<int>("bill_Discount")
                        .HasColumnType("int");

                    b.Property<bool>("bill_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("bill_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bill_PaidTotal")
                        .HasColumnType("int");

                    b.Property<string>("bill_PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductColorlist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductIdlist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductNamelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductPricelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductSizelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bill_Shipping")
                        .HasColumnType("int");

                    b.Property<string>("bill_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_WaitForConfirmation")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_WaitPickup")
                        .HasColumnType("bit");

                    b.HasKey("bill_Id");

                    b.HasIndex("bill_UserId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            bill_Id = "D269BF93-A5E2-4C4A-8146-9967DDE80D30",
                            bill_Cancelled = false,
                            bill_Confirmation = true,
                            bill_DatetimeOrder = new DateTime(2022, 3, 30, 23, 33, 13, 61, DateTimeKind.Local).AddTicks(8218),
                            bill_Delivered = false,
                            bill_Delivering = false,
                            bill_Discount = 0,
                            bill_HideStatus = false,
                            bill_Note = "",
                            bill_PaidTotal = 2000,
                            bill_PaymentMethod = "Check Payment",
                            bill_ProductColorlist = "Blue|Red|Black|Green|",
                            bill_ProductIdlist = "1|2|3|4",
                            bill_ProductNamelist = "product 1|product 2| product 3| product 4|",
                            bill_ProductPricelist = "550|450|350|640|",
                            bill_ProductSizelist = "7|8|9|14|",
                            bill_Quantity = "1|1|2|1|",
                            bill_Shipping = 10,
                            bill_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            bill_WaitForConfirmation = false,
                            bill_WaitPickup = false
                        });
                });

            modelBuilder.Entity("Food.Entity.Cart", b =>
                {
                    b.Property<string>("cart_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cart_UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("cart_Id");

                    b.HasIndex("cart_UserID");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            cart_Id = "72309286-ECBB-4D20-AD95-2819D31E3400",
                            cart_UserID = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff"
                        },
                        new
                        {
                            cart_Id = "D355458F-1DD3-4834-AA28-6DA34B6357FF",
                            cart_UserID = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        });
                });

            modelBuilder.Entity("Food.Entity.CartsDevice", b =>
                {
                    b.Property<string>("cartd_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cartd_DeviceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("cartd_Id");

                    b.HasIndex("cartd_DeviceId");

                    b.ToTable("CartsDevice");
                });

            modelBuilder.Entity("Food.Entity.Categories", b =>
                {
                    b.Property<string>("cg_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cg_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cg_Sale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cg_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cg_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            cg_Id = "28df707b-0078-47d1-9b8f-6cf4cb6a6d83",
                            cg_Name = "Dry food",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "e765d5e0-09e5-4545-a116-9846a9ca4641",
                            cg_Name = "Food",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "52cc96f7-1091-4fa5-b11f-4ca0ae50f54d",
                            cg_Name = "Drink",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "0db26f60-12de-494d-ba5a-ee4aea3790bf",
                            cg_Name = "Banhmi",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "a76987aa-a733-4d33-9a22-d0b80adc83ea",
                            cg_Name = "Snack",
                            cg_Sale = "",
                            cg_Type = ""
                        });
                });

            modelBuilder.Entity("Food.Entity.ContactSystem", b =>
                {
                    b.Property<int>("Contact_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contact_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Contact_Id");

                    b.ToTable("ContactSystems");
                });

            modelBuilder.Entity("Food.Entity.ContactUsers", b =>
                {
                    b.Property<string>("cu_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cu_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cu_Id");

                    b.ToTable("ContactUsers");

                    b.HasData(
                        new
                        {
                            cu_Id = "50372a5b-b93f-4b9f-a6ee-acea1eceda0f",
                            cu_Description = "Description",
                            cu_Email = "Email",
                            cu_FirstName = "FirstName",
                            cu_LastName = "LastName",
                            cu_Subject = "Subject"
                        });
                });

            modelBuilder.Entity("Food.Entity.Coupons", b =>
                {
                    b.Property<string>("couponId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("couponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("couponPrice")
                        .HasColumnType("int");

                    b.HasKey("couponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            couponId = "d7730026-cc1f-4bce-ad04-944f6aeccf02",
                            couponCode = "code10",
                            couponPrice = 10
                        },
                        new
                        {
                            couponId = "fdbbd735-affd-4b00-9bbd-f7d0b2d17454",
                            couponCode = "code50",
                            couponPrice = 50
                        });
                });

            modelBuilder.Entity("Food.Entity.Device", b =>
                {
                    b.Property<string>("deviceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("deviceAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devicePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devicePostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceState")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("deviceId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("Food.Entity.ProductInCart", b =>
                {
                    b.Property<string>("pic_CartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pic_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("pic_amount")
                        .HasColumnType("int");

                    b.Property<string>("pic_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pic_size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pic_CartId", "pic_ProductId");

                    b.HasIndex("pic_ProductId");

                    b.ToTable("ProductInCart");
                });

            modelBuilder.Entity("Food.Entity.ProductInCartDevices", b =>
                {
                    b.Property<string>("picd_CartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("picd_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("picd_amount")
                        .HasColumnType("int");

                    b.Property<string>("picd_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picd_size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("picd_CartId", "picd_ProductId");

                    b.HasIndex("picd_ProductId");

                    b.ToTable("ProductInCartDevices");
                });

            modelBuilder.Entity("Food.Entity.Products", b =>
                {
                    b.Property<string>("pd_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pd_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pd_Price")
                        .HasColumnType("int");

                    b.Property<int>("pd_Rate")
                        .HasColumnType("int");

                    b.Property<int>("pd_ReducePrice")
                        .HasColumnType("int");

                    b.Property<string>("pd_ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pd_WaitForConfirmation")
                        .HasColumnType("bit");

                    b.HasKey("pd_Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            pd_Id = "3d3258bd-a41e-40ed-951c-7ba810fa79d6",
                            pd_Description = "BanhCanhCua",
                            pd_Img1 = "/images/item250x300/BanhCanhCua.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "BanhCanhCua",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "a8408455-de4a-4e82-9a53-0e4b5c38d6bb",
                            pd_Description = "BanhMi",
                            pd_Img1 = "/images/item250x300/BanhMi.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "BanhMi",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "b3f737cd-a27b-4f3b-93b2-af2f267d1d22",
                            pd_Description = "banhtrangtron",
                            pd_Img1 = "/images/item250x300/banhtrangtron.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "banhtrangtron",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "7f9af334-9f6a-4eed-81b9-2f1f0c6e60ad",
                            pd_Description = "banhuotlongdalat",
                            pd_Img1 = "/images/item250x300/banhuotlongdalat.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "banhuotlongdalat",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "0a03add5-e870-4e6d-830f-27ebf48ada0e",
                            pd_Description = "BoKho",
                            pd_Img1 = "/images/item250x300/BoKho.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "BoKho",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "1b1d757e-84fd-49e8-bf11-2f88cdfe9d2a",
                            pd_Description = "bunbo",
                            pd_Img1 = "/images/item250x300/bunbo.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "bunbo",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "9ff456da-5772-4c09-9985-d9def0838f29",
                            pd_Description = "bundaumamtom",
                            pd_Img1 = "/images/item250x300/bundaumamtom.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "bundaumamtom",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "72adda5b-3c9f-4734-80d7-cba57ccb793a",
                            pd_Description = "Bunxaochay",
                            pd_Img1 = "/images/item250x300/Bunxaochay.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Bunxaochay",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "7c009ed6-6158-4b6c-b4fc-03e4eaacdd96",
                            pd_Description = "cocosummer",
                            pd_Img1 = "/images/item250x300/cocosummer.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "cocosummer",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "032c4f34-2995-460a-afe1-a389e9dad8e2",
                            pd_Description = "comboxao",
                            pd_Img1 = "/images/item250x300/comboxao.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "comboxao",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "a0084efb-5ed9-4f5e-ad69-9176c98a0c07",
                            pd_Description = "comga",
                            pd_Img1 = "/images/item250x300/comga.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "comga",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "5e05a7b6-690f-4848-9d38-e1b66cbb52b8",
                            pd_Description = "comgadenhat",
                            pd_Img1 = "/images/item250x300/comgadenhat.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "comgadenhat",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "e9e4a2ed-7589-4914-b15e-c9d8a9b0aa6b",
                            pd_Description = "denhatthitnuong",
                            pd_Img1 = "/images/item250x300/denhatthitnuong.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "denhatthitnuong",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "e87c8e9b-408c-48f1-93d7-a2d36f7a263f",
                            pd_Description = "goicuon",
                            pd_Img1 = "/images/item250x300/goicuon.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "goicuon",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "9c0baf9c-49b5-4ca1-8b1f-02bf89c75ec4",
                            pd_Description = "kfc",
                            pd_Img1 = "/images/item250x300/kfc.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "kfc",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "5b2cb1f0-41d6-4466-924d-5291983e4b41",
                            pd_Description = "KimBap",
                            pd_Img1 = "/images/item250x300/KimBap.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "KimBap",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "a1263392-68f8-4725-ac4a-ce623789ef1c",
                            pd_Description = "loteria",
                            pd_Img1 = "/images/item250x300/loteria.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "loteria",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "ee3ca309-05df-41e7-a54b-73d9d333c2ad",
                            pd_Description = "mitronanvat",
                            pd_Img1 = "/images/item250x300/mitronanvat.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "mitronanvat",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "c41afb49-410d-46f7-92c5-940721cdeda6",
                            pd_Description = "monngontrangbang",
                            pd_Img1 = "/images/item250x300/monngontrangbang.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "monngontrangbang",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "838d31f1-e61d-4496-94cf-35a71900428e",
                            pd_Description = "ParisBaguete",
                            pd_Img1 = "/images/item250x300/ParisBaguete.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "ParisBaguete",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "97205c46-070c-4f46-9b93-1da7670d3dda",
                            pd_Description = "pizza",
                            pd_Img1 = "/images/item250x300/pizza.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "pizza",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "c7acc2ab-a16d-4cca-8ba8-407042234dac",
                            pd_Description = "quanngontrangbang",
                            pd_Img1 = "/images/item250x300/quanngontrangbang.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "quanngontrangbang",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "55516884-07cc-453a-8d17-67f30d44e611",
                            pd_Description = "RauMaMix",
                            pd_Img1 = "/images/item250x300/RauMaMix.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "RauMaMix",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "1dfe7d30-f5f6-4be2-a91d-3d225e8ca58d",
                            pd_Description = "Royaltea",
                            pd_Img1 = "/images/item250x300/Royaltea.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Royaltea",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "3cbcd29c-c84e-45e7-835a-7208abd9561a",
                            pd_Description = "Sanfulou",
                            pd_Img1 = "/images/item250x300/Sanfulou.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Sanfulou",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "3f7ee889-6b6d-421b-9c9f-214dc571a8cd",
                            pd_Description = "stacbuk-cf",
                            pd_Img1 = "/images/item250x300/stacbuk-cf.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "stacbuk-cf",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "40e78adc-26ed-49f8-be52-d2b8c9a630de",
                            pd_Description = "trasuanhalam",
                            pd_Img1 = "/images/item250x300/trasuanhalam.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "trasuanhalam",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "362c768a-4828-4dbf-bb7b-8ed1b899ee9e",
                            pd_Description = "Xoixeoba3beo",
                            pd_Img1 = "/images/item250x300/Xoixeoba3beo.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Xoixeoba3beo",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        });
                });

            modelBuilder.Entity("Food.Entity.ProductsInCategories", b =>
                {
                    b.Property<string>("pic_productId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pic_CategoriesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("pic_productId", "pic_CategoriesId");

                    b.HasIndex("pic_CategoriesId");

                    b.ToTable("ProductsInCategories");

                    b.HasData(
                        new
                        {
                            pic_productId = "9ff456da-5772-4c09-9985-d9def0838f29",
                            pic_CategoriesId = "28df707b-0078-47d1-9b8f-6cf4cb6a6d83"
                        },
                        new
                        {
                            pic_productId = "72adda5b-3c9f-4734-80d7-cba57ccb793a",
                            pic_CategoriesId = "28df707b-0078-47d1-9b8f-6cf4cb6a6d83"
                        },
                        new
                        {
                            pic_productId = "032c4f34-2995-460a-afe1-a389e9dad8e2",
                            pic_CategoriesId = "28df707b-0078-47d1-9b8f-6cf4cb6a6d83"
                        },
                        new
                        {
                            pic_productId = "a0084efb-5ed9-4f5e-ad69-9176c98a0c07",
                            pic_CategoriesId = "28df707b-0078-47d1-9b8f-6cf4cb6a6d83"
                        },
                        new
                        {
                            pic_productId = "5e05a7b6-690f-4848-9d38-e1b66cbb52b8",
                            pic_CategoriesId = "28df707b-0078-47d1-9b8f-6cf4cb6a6d83"
                        },
                        new
                        {
                            pic_productId = "e9e4a2ed-7589-4914-b15e-c9d8a9b0aa6b",
                            pic_CategoriesId = "28df707b-0078-47d1-9b8f-6cf4cb6a6d83"
                        },
                        new
                        {
                            pic_productId = "e87c8e9b-408c-48f1-93d7-a2d36f7a263f",
                            pic_CategoriesId = "28df707b-0078-47d1-9b8f-6cf4cb6a6d83"
                        },
                        new
                        {
                            pic_productId = "5b2cb1f0-41d6-4466-924d-5291983e4b41",
                            pic_CategoriesId = "28df707b-0078-47d1-9b8f-6cf4cb6a6d83"
                        },
                        new
                        {
                            pic_productId = "3d3258bd-a41e-40ed-951c-7ba810fa79d6",
                            pic_CategoriesId = "e765d5e0-09e5-4545-a116-9846a9ca4641"
                        },
                        new
                        {
                            pic_productId = "7f9af334-9f6a-4eed-81b9-2f1f0c6e60ad",
                            pic_CategoriesId = "e765d5e0-09e5-4545-a116-9846a9ca4641"
                        },
                        new
                        {
                            pic_productId = "0a03add5-e870-4e6d-830f-27ebf48ada0e",
                            pic_CategoriesId = "e765d5e0-09e5-4545-a116-9846a9ca4641"
                        },
                        new
                        {
                            pic_productId = "1b1d757e-84fd-49e8-bf11-2f88cdfe9d2a",
                            pic_CategoriesId = "e765d5e0-09e5-4545-a116-9846a9ca4641"
                        },
                        new
                        {
                            pic_productId = "c41afb49-410d-46f7-92c5-940721cdeda6",
                            pic_CategoriesId = "e765d5e0-09e5-4545-a116-9846a9ca4641"
                        },
                        new
                        {
                            pic_productId = "55516884-07cc-453a-8d17-67f30d44e611",
                            pic_CategoriesId = "52cc96f7-1091-4fa5-b11f-4ca0ae50f54d"
                        },
                        new
                        {
                            pic_productId = "1dfe7d30-f5f6-4be2-a91d-3d225e8ca58d",
                            pic_CategoriesId = "52cc96f7-1091-4fa5-b11f-4ca0ae50f54d"
                        },
                        new
                        {
                            pic_productId = "3f7ee889-6b6d-421b-9c9f-214dc571a8cd",
                            pic_CategoriesId = "52cc96f7-1091-4fa5-b11f-4ca0ae50f54d"
                        },
                        new
                        {
                            pic_productId = "40e78adc-26ed-49f8-be52-d2b8c9a630de",
                            pic_CategoriesId = "52cc96f7-1091-4fa5-b11f-4ca0ae50f54d"
                        },
                        new
                        {
                            pic_productId = "a8408455-de4a-4e82-9a53-0e4b5c38d6bb",
                            pic_CategoriesId = "0db26f60-12de-494d-ba5a-ee4aea3790bf"
                        },
                        new
                        {
                            pic_productId = "ee3ca309-05df-41e7-a54b-73d9d333c2ad",
                            pic_CategoriesId = "0db26f60-12de-494d-ba5a-ee4aea3790bf"
                        },
                        new
                        {
                            pic_productId = "b3f737cd-a27b-4f3b-93b2-af2f267d1d22",
                            pic_CategoriesId = "a76987aa-a733-4d33-9a22-d0b80adc83ea"
                        },
                        new
                        {
                            pic_productId = "7c009ed6-6158-4b6c-b4fc-03e4eaacdd96",
                            pic_CategoriesId = "a76987aa-a733-4d33-9a22-d0b80adc83ea"
                        },
                        new
                        {
                            pic_productId = "9c0baf9c-49b5-4ca1-8b1f-02bf89c75ec4",
                            pic_CategoriesId = "a76987aa-a733-4d33-9a22-d0b80adc83ea"
                        },
                        new
                        {
                            pic_productId = "a1263392-68f8-4725-ac4a-ce623789ef1c",
                            pic_CategoriesId = "a76987aa-a733-4d33-9a22-d0b80adc83ea"
                        },
                        new
                        {
                            pic_productId = "838d31f1-e61d-4496-94cf-35a71900428e",
                            pic_CategoriesId = "a76987aa-a733-4d33-9a22-d0b80adc83ea"
                        },
                        new
                        {
                            pic_productId = "97205c46-070c-4f46-9b93-1da7670d3dda",
                            pic_CategoriesId = "a76987aa-a733-4d33-9a22-d0b80adc83ea"
                        },
                        new
                        {
                            pic_productId = "c7acc2ab-a16d-4cca-8ba8-407042234dac",
                            pic_CategoriesId = "a76987aa-a733-4d33-9a22-d0b80adc83ea"
                        },
                        new
                        {
                            pic_productId = "3cbcd29c-c84e-45e7-835a-7208abd9561a",
                            pic_CategoriesId = "a76987aa-a733-4d33-9a22-d0b80adc83ea"
                        },
                        new
                        {
                            pic_productId = "362c768a-4828-4dbf-bb7b-8ed1b899ee9e",
                            pic_CategoriesId = "a76987aa-a733-4d33-9a22-d0b80adc83ea"
                        });
                });

            modelBuilder.Entity("Food.Entity.ReviewInproduct", b =>
                {
                    b.Property<string>("rip_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("rip_ReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("rip_ProductId", "rip_ReviewId");

                    b.HasIndex("rip_ReviewId");

                    b.ToTable("ReviewInproduct");

                    b.HasData(
                        new
                        {
                            rip_ProductId = "3d3258bd-a41e-40ed-951c-7ba810fa79d6",
                            rip_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C"
                        },
                        new
                        {
                            rip_ProductId = "3d3258bd-a41e-40ed-951c-7ba810fa79d6",
                            rip_ReviewId = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97"
                        },
                        new
                        {
                            rip_ProductId = "3d3258bd-a41e-40ed-951c-7ba810fa79d6",
                            rip_ReviewId = "C2A543C2-B1E2-4DC5-A131-9137E4673FA6"
                        });
                });

            modelBuilder.Entity("Food.Entity.Reviews", b =>
                {
                    b.Property<string>("review_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("review_Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("review_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("review_ReviewType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("review_UploadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("review_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("review_id");

                    b.HasIndex("review_UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            review_id = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            review_Comment = "Good1",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        },
                        new
                        {
                            review_id = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97",
                            review_Comment = "Good2",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff"
                        },
                        new
                        {
                            review_id = "C2A543C2-B1E2-4DC5-A131-9137E4673FA6",
                            review_Comment = "Good3",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        });
                });

            modelBuilder.Entity("Food.Entity.Shipping", b =>
                {
                    b.Property<string>("ship_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ship_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ship_Price")
                        .HasColumnType("int");

                    b.HasKey("ship_Id");

                    b.ToTable("Shipping");

                    b.HasData(
                        new
                        {
                            ship_Id = "7CF94A7D-9239-446E-A404-086518F84652",
                            ship_Name = "Ship",
                            ship_Price = 5
                        });
                });

            modelBuilder.Entity("Food.Entity.SubReview", b =>
                {
                    b.Property<string>("subReview_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("subReview_Commnet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("subReview_DateCommnet")
                        .HasColumnType("datetime2");

                    b.Property<bool>("subReview_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("subReview_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("subreview_SubReviewType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subReview_Id");

                    b.HasIndex("subReview_UserId");

                    b.ToTable("SubReview");

                    b.HasData(
                        new
                        {
                            subReview_Id = "77ba56ea-2f2c-4bff-a6a9-4ae32ded6c9a",
                            subReview_Commnet = "subreview 1",
                            subReview_DateCommnet = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            subreview_SubReviewType = "SubReview"
                        },
                        new
                        {
                            subReview_Id = "d0015fc0-18bc-4428-93dd-d90fb37c187d",
                            subReview_Commnet = "subreview 3",
                            subReview_DateCommnet = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            subreview_SubReviewType = "SubReview"
                        },
                        new
                        {
                            subReview_Id = "0019b95d-ef43-4069-b6fe-897cdae04b86",
                            subReview_Commnet = "subreview 3",
                            subReview_DateCommnet = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            subreview_SubReviewType = "SubReview"
                        });
                });

            modelBuilder.Entity("Food.Entity.SubReviewInReview", b =>
                {
                    b.Property<string>("SRiR_ReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SRiR_SubReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SRiR_ReviewId", "SRiR_SubReviewId");

                    b.HasIndex("SRiR_SubReviewId");

                    b.ToTable("SubReviewInReview");

                    b.HasData(
                        new
                        {
                            SRiR_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            SRiR_SubReviewId = "77ba56ea-2f2c-4bff-a6a9-4ae32ded6c9a"
                        },
                        new
                        {
                            SRiR_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            SRiR_SubReviewId = "d0015fc0-18bc-4428-93dd-d90fb37c187d"
                        },
                        new
                        {
                            SRiR_ReviewId = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97",
                            SRiR_SubReviewId = "0019b95d-ef43-4069-b6fe-897cdae04b86"
                        });
                });

            modelBuilder.Entity("Food.Entity.SubscribeEmail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscribeEmail");
                });

            modelBuilder.Entity("Food.Models.UserInRoleModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("UserInRoleModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            RoleId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd"
                        },
                        new
                        {
                            UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            RoleId = "360E601E-92F2-4F08-832B-604A21293258"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Food.Entity.AppRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Roles");

                    b.HasDiscriminator().HasValue("AppRole");

                    b.HasData(
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd",
                            ConcurrencyStamp = "87b47d8c-9b16-4a7e-9578-32774719d818",
                            Name = "Staff",
                            NormalizedName = "staff",
                            Description = "Staff"
                        },
                        new
                        {
                            Id = "360E601E-92F2-4F08-832B-604A21293258",
                            ConcurrencyStamp = "a63bb06c-3bba-4dd9-930b-954ffa5b3f28",
                            Name = "Admin",
                            NormalizedName = "admin",
                            Description = "Admin"
                        });
                });

            modelBuilder.Entity("Food.Entity.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_State")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("AppUser");

                    b.HasData(
                        new
                        {
                            Id = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6716582-dab1-4787-8621-7b58a47ade53",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIIrs1JnQuZDlorOpt0zv8bJpiLVfzte5pdFtC3YjcIphMTHzzbHqrQE5l2oPMGR4w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3f7d6f51-3f7a-4b4c-9956-0b0412fceb45",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            DoB = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "admin",
                            LastName = "admin"
                        },
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8322b4ce-e047-4894-a37d-bd8efc1472fa",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEO8u8S1zlS5WLmSBKVYGDLNQXhJJZn2rIKoo/b9RcAvEqts0P4CU+vn5STIs5bRqqQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5cfaa53-19f9-41aa-80c7-0c16c67b1dd1",
                            TwoFactorEnabled = false,
                            UserName = "Staff",
                            DoB = new DateTime(2020, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "staff",
                            LastName = "staff"
                        });
                });

            modelBuilder.Entity("Food.Entity.Bills", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserB")
                        .WithMany("BillsAU")
                        .HasForeignKey("bill_UserId");

                    b.Navigation("AppUserB");
                });

            modelBuilder.Entity("Food.Entity.Cart", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserC")
                        .WithMany("CartU")
                        .HasForeignKey("cart_UserID");

                    b.Navigation("AppUserC");
                });

            modelBuilder.Entity("Food.Entity.CartsDevice", b =>
                {
                    b.HasOne("Food.Entity.Device", "DeviceCD")
                        .WithMany("CartsDeviceD")
                        .HasForeignKey("cartd_DeviceId");

                    b.Navigation("DeviceCD");
                });

            modelBuilder.Entity("Food.Entity.ProductInCart", b =>
                {
                    b.HasOne("Food.Entity.Cart", "CartPICart")
                        .WithMany("ProductInCartC")
                        .HasForeignKey("pic_CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Products", "ProductsPICart")
                        .WithMany("ProductInCartP")
                        .HasForeignKey("pic_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartPICart");

                    b.Navigation("ProductsPICart");
                });

            modelBuilder.Entity("Food.Entity.ProductInCartDevices", b =>
                {
                    b.HasOne("Food.Entity.CartsDevice", "CartsDevicePICD")
                        .WithMany("ProductInCartDevicesCD")
                        .HasForeignKey("picd_CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Products", "ProductsPICD")
                        .WithMany("ProductInCartDevicesP")
                        .HasForeignKey("picd_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartsDevicePICD");

                    b.Navigation("ProductsPICD");
                });

            modelBuilder.Entity("Food.Entity.ProductsInCategories", b =>
                {
                    b.HasOne("Food.Entity.Categories", "CategoriesPIC")
                        .WithMany("ProductsInCategoriesC")
                        .HasForeignKey("pic_CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Products", "ProductsPIC")
                        .WithMany("ProductsInCategoriesP")
                        .HasForeignKey("pic_productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriesPIC");

                    b.Navigation("ProductsPIC");
                });

            modelBuilder.Entity("Food.Entity.ReviewInproduct", b =>
                {
                    b.HasOne("Food.Entity.Products", "ProductsRIP")
                        .WithMany("ReviewInproductP")
                        .HasForeignKey("rip_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Reviews", "ReviewsRIP")
                        .WithMany("ReviewInproductR")
                        .HasForeignKey("rip_ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductsRIP");

                    b.Navigation("ReviewsRIP");
                });

            modelBuilder.Entity("Food.Entity.Reviews", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserR")
                        .WithMany("ReviewsU")
                        .HasForeignKey("review_UserId");

                    b.Navigation("AppUserR");
                });

            modelBuilder.Entity("Food.Entity.SubReview", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserSR")
                        .WithMany("SubReviewSR")
                        .HasForeignKey("subReview_UserId");

                    b.Navigation("AppUserSR");
                });

            modelBuilder.Entity("Food.Entity.SubReviewInReview", b =>
                {
                    b.HasOne("Food.Entity.Reviews", "Reviews")
                        .WithMany("SubReviewInReview")
                        .HasForeignKey("SRiR_ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.SubReview", "SubReview")
                        .WithMany("SubReviewInReview")
                        .HasForeignKey("SRiR_SubReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviews");

                    b.Navigation("SubReview");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Food.Entity.Cart", b =>
                {
                    b.Navigation("ProductInCartC");
                });

            modelBuilder.Entity("Food.Entity.CartsDevice", b =>
                {
                    b.Navigation("ProductInCartDevicesCD");
                });

            modelBuilder.Entity("Food.Entity.Categories", b =>
                {
                    b.Navigation("ProductsInCategoriesC");
                });

            modelBuilder.Entity("Food.Entity.Device", b =>
                {
                    b.Navigation("CartsDeviceD");
                });

            modelBuilder.Entity("Food.Entity.Products", b =>
                {
                    b.Navigation("ProductInCartDevicesP");

                    b.Navigation("ProductInCartP");

                    b.Navigation("ProductsInCategoriesP");

                    b.Navigation("ReviewInproductP");
                });

            modelBuilder.Entity("Food.Entity.Reviews", b =>
                {
                    b.Navigation("ReviewInproductR");

                    b.Navigation("SubReviewInReview");
                });

            modelBuilder.Entity("Food.Entity.SubReview", b =>
                {
                    b.Navigation("SubReviewInReview");
                });

            modelBuilder.Entity("Food.Entity.AppUser", b =>
                {
                    b.Navigation("BillsAU");

                    b.Navigation("CartU");

                    b.Navigation("ReviewsU");

                    b.Navigation("SubReviewSR");
                });
#pragma warning restore 612, 618
        }
    }
}
